<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>my-webapp</artifactId>
  <packaging>war</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <name>my-webapp Maven Webapp</name>
  <url>http://maven.apache.org</url>
  <dependencies>
  
<!--    / <dependency> -->
<!--         <groupId>com.example</groupId> -->
<!--   <artifactId>my-shared-library</artifactId> -->
<!--   <version>0.0.1-SNAPSHOT</version> -->
<!--     </dependency> -->


    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  
  <build>
    <finalName>my-webapp</finalName>
  </build>
  <distributionManagement>
    <repository>
        <id>central</id>
        <name>a0ceddtod3tfz-artifactory-primary-0-releases</name>
        <url>https://trialgl5st5.jfrog.io/artifactory/maven-local-demo00</url>
    </repository>
    <snapshotRepository>
        <id>snapshots</id>
        <name>a0ceddtod3tfz-artifactory-primary-0-snapshots</name>
        <url>https://trialgl5st5.jfrog.io/artifactory/maven-local-demo00</url>
    </snapshotRepository>
</distributionManagement>
</project>
